name: towerclimbonline

environment:
  sdk: '^3.1.3'

# ngdart and ngforms are no longer compatible with webdev
# dart 3 migration might be impossible

dependencies:
  ngdart: any
  ngforms: any
  crypto: any
  image: ^3.3.0
  intl: any
  logging: any
  mailer: any
  pathfinding: any
  piecemeal: any
  postgresql2: any
  quiver: any
  r_tree: any
  yaml: any
  collection: any

dev_dependencies:
  test: any
  build_runner: any
  build_web_compilers: any