name: towerclimbonline

environment:
  sdk: '2.10.5'

dependencies:
  angular: any
  angular_forms: any
  crypto: any
  image: 2.1.13
  intl: any
  logging: any
  mailer: any
  pathfinding: any
  piecemeal: any
  postgresql2: any
  quiver: any
  r_tree: any
  yaml: any

dev_dependencies:
  test: any
  build_runner: any
  build_web_compilers: any